name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image from Dockerfile-1
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          shingyu/fanqie-downloader-api-v4:mysql
          shingyu/fanqie-downloader-api-v4:latest

    - name: Build and push image from Dockerfile-2
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.nomysql
        push: true
        tags: |
          shingyu/fanqie-downloader-api-v4:nomysql
