name: Build and Push Docker Images

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get tag name
      id: get_tag
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

    - name: Build and push image from Dockerfile-1
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          shingyu/fanqie-downloader-api-v4:${{ steps.get_tag.outputs.TAG_NAME }}-mysql
          shingyu/fanqie-downloader-api-v4:latest-mysql
          shingyu/fanqie-downloader-api-v4:latest

    - name: Build and push image from Dockerfile-2
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.nomysql
        push: true
        tags: |
          shingyu/fanqie-downloader-api-v4:${{ steps.get_tag.outputs.TAG_NAME }}-nomysql
          shingyu/fanqie-downloader-api-v4:latest-nomysql
